### ISSUE TITLE
css issues

### ISSUE THREAD

**Issue by MashalMohammed** [RITct/ritct.github.io#11]
inline css is working fine for both bg image and color.

i cant put background image or background color, via  home.css:
```css
body
{
  padding-left: 0px;
  padding-right: 0px;
  background-color:#555555;
}
```

this too , not working:
 `background-image:url(/assets/images/bg.bmp);`

btw, me **newbie**
